import Head from 'next/head';
import { Box } from '@mantine/core';
import { useState } from 'react';
import { useSession } from 'next-auth/react';
import UploadModal from '@/components/Modals/UploadModal/UploadModal';
import Navbar from '@/components/Navbar/Navbar';
import { useRouter } from 'next/router';
import { useQuery } from 'react-query';

const fetchClientImages = async () => {
	const retVal = [];
	const response = await fetch(`/api/images/get`, {
		method: 'GET',
	});
};

export default function Images() {
	const router = useRouter();
	const { data: session, status } = useSession();

	if (status === 'unauthenticated') {
		void router.push('/');
	}

	const [isOpen, setIsOpen] = useState(false);
	const toggleUploadModal = () => {
		setIsOpen(true);
	};

	const clientImages = useQuery('images', fetchClientImages);

	return (
		<>
			<Head>
				<title>Cf Wrapper - My images</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Box
				sx={{
					height: '100vh',
					width: '100%',
					backgroundImage: 'linear-gradient(to bottom, rgb(38, 38, 38, 0.9) 10%, rgb(13, 13, 13))',
				}}
			>
				<Box
					component='main'
					sx={{
						height: '100%',
						margin: '0 auto',
						maxWidth: '1200px',
						display: 'flex',
						flexDirection: 'column',
						position: 'relative',
					}}
				>
					<Navbar toggleUploadModal={toggleUploadModal} />
					<Box
						sx={{
							display: 'grid',
							gridTemplateColumns: 'repeat(2, 1fr)',
							gap: '6rem',
							height: '100%',
							width: '100%',
						}}
					>
						{/* <ImageComp />
						<Header setIsOpen={setIsOpen} /> */}
					</Box>

					<UploadModal isOpen={isOpen} setIsOpen={setIsOpen} />
					<Box component='footer'></Box>
				</Box>
			</Box>
		</>
	);
}
